### ISSUE TITLE
Package installation issue with pyproj

### ISSUE THREAD

**Issue by htulet** [umr-amap/iamap#17]
After the packages missing for the plugin were instaled (seemingly successfully), when I tried to activate the plugon in QGIS, I got the following error, meaning I can't use the plugin tools : 
```
Impossible de charger l'extension 'iamap' provoque une erreur lors de l'appel à sa méthode classFactory() 

rasterio.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: C:\PROGRA~1\QGIS33~1.3\share\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation. 
Traceback (most recent call last):
  File "rasterio\\crs.pyx", line 586, in rasterio.crs.CRS.from_epsg
  File "rasterio\\_err.pyx", line 195, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_AppDefinedError: PROJ: proj_create_from_database: C:\PROGRA~1\QGIS33~1.3\share\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/tulet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iamap\__init__.py", line 9, in classFactory
    from .iamap import IAMap
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tulet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iamap\iamap.py", line 11, in 
    from .provider import IAMapProvider
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tulet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iamap\provider.py", line 3, in 
    from .encoder import EncoderAlgorithm
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tulet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iamap\encoder.py", line 51, in 
    from torchgeo.datasets import RasterDataset, BoundingBox,stack_samples
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\tulet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\iamap\python3.9\torchgeo\datasets\__init__.py", line 6, in 
    from .advance import ADVANCE
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\tulet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\iamap\python3.9\torchgeo\datasets\advance.py", line 17, in 
    from .geo import NonGeoDataset
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\tulet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\iamap\python3.9\torchgeo\datasets\geo.py", line 42, in 
    class GeoDataset(Dataset[dict[str, Any]], abc.ABC):
  File "C:\Users\tulet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\iamap\python3.9\torchgeo\datasets\geo.py", line 85, in GeoDataset
    _crs = CRS.from_epsg(4326)
  File "rasterio\\crs.pyx", line 590, in rasterio.crs.CRS.from_epsg
rasterio.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: C:\PROGRA~1\QGIS33~1.3\share\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.


Version de Python : 3.9.18 (heads/master:c290dc6, Jan 14 2024, 01:36:02) [MSC v.1929 64 bit (AMD64)] 
Version de QGIS : 3.34.3-Prizren Prizren, 47373234ac 
```

I am on Windows and tried the cpu and gpu version, both giving the same result shown above.

**Comment by htulet** [comment]
Update : Retrograding to rasterio 1.3 and pyproj 3.6 has fixed the issue

**Comment by ptresson** [comment]
> Update : Retrograding to rasterio 1.3 and pyproj 3.6 has fixed the issue

Allright, I'm closing this issue
